name: crypto_freebie
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0-182.1.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  sizer: ^2.0.13
  get: ^4.6.1
  get_storage: ^2.0.3
  google_fonts: ^2.3.2
  settings_ui: ^2.0.2
  flutter_dotenv: ^5.0.2
  fl_chart: ^0.50.1
  auto_size_text: ^3.0.0
  floor: ^1.2.0
  sqflite: ^2.0.2
  flutter_secure_storage: ^5.0.2
  freezed_annotation:
  dio: ^4.0.4
  retrofit: 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner:
  freezed:
  json_serializable:
  retrofit_generator:
  floor_generator:

flutter:
  uses-material-design: true

  assets:
    - .env
