name: crypto_freebie
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0-182.1.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.1.0
  sizer: ^2.0.13
  intl: ^0.17.0
  get: ^4.6.1
  uuid: ^3.0.6
  hidable: ^1.0.2
  get_storage: ^2.0.3
  google_fonts: ^2.3.2
  settings_ui: ^1.0.0
  flutter_dotenv: ^5.0.2
  shimmer: ^2.0.0
  flutter_spinkit: ^5.1.0
  google_nav_bar: ^5.0.6
  fl_chart: ^0.36.1
  auto_size_text: ^3.0.0
  floor: ^1.2.0
  sqflite: ^2.0.2
  flutter_candlesticks:
    git: https://github.com/salvadordeveloper/flutter-candlesticks.git
  freezed_annotation:
  dio: ^4.0.4
  retrofit: 
  json_annotation: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  analyzer: 
  flutter_lints: ^1.0.0
  build_runner:
  freezed:
  json_serializable:
  retrofit_generator:
  floor_generator:

flutter:
  uses-material-design: true

  assets:
    - .env
